# Generated by Django 4.0.1 on 2022-02-18 01:25

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.generateCode, max_length=10, unique=True),
        ),
    ]
